### ISSUE TITLE
about log

### ISSUE THREAD

**Issue by wangyuuu** [jimmy-dq/DropTrack#1]
thanks for your pretrained-models, could you give me your training logs about Droptrack

**Comment by jimmy-dq** [comment]
> thanks for your pretrained-models, could you give me your training logs about Droptrack

@wangyuuu sorry for the late reply. The training log of DropTrack for GOT-10k can be found in [here](https://github.com/jimmy-dq/DropTrack/blob/main/droptrack-vitb_384_mae_ce_32x4_got10k_ep100.log).
