### ISSUE TITLE
ONNX convertion

### ISSUE THREAD

**Issue by MUHAMMEDZEYN** [jimmy-dq/DropTrack#2]
Thanks for your great work, I have been working with this topic for a long time and I am really impressed with your work. I want to ask you if you are planning to convert your model to onnx ?

**Comment by jimmy-dq** [comment]
Hi, thanks for your interests. Recently we do not have this plan, if you want, you could use our provided source codes and pytorch models to do so.

**Comment by MUHAMMEDZEYN** [comment]
@joseasanchezgonzalez  I did not work on it actually, if anything happens I will update the comment.
