### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by June-hui** [jimmy-dq/DropTrack#3]
Thank for your great work, but when i follow your work to install reqirement.txt, can't install the package well. Did you install package with this command "pip install -r requirement.txt" ? Hope your reply~

**Comment by jimmy-dq** [comment]
> Thank for your great work, but when i follow your work to install reqirement.txt, can't install the package well. Did you install package with this command "pip install -r requirement.txt" ? Hope your reply~

Hi hui, is there any specific reported errors by using this installation command? Additionally, you can also follow the installation steps introduced in OSTrack for installation.

**Comment by June-hui** [comment]
thank you for your reply
